name: CurlCraft
version: 0.0.1
api-version: 1.15
description: The Minecraft plugin that adds RESTful API endpoints to your server, allowing for an unlimited amount of crazy.

author: irritatingness 
website: irritatingness.com

main: com.irritatingness.CurlCraft
